/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Category Configuration Content
 * This file contains all category definitions for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Generated: 2025-12-01T19:04:22.780Z
 */

import type { Category } from './categories.schema'

/**
 * Blog categories with nested subcategories
 * Auto-populated from brand database (BrandCategory table)
 */
export const categories: Category[] = [
  {
    id: "d66436f7-7f0e-4220-93eb-66eccdb5c424",
    name: "Geological Phenomena",
    slug: "geological-phenomena",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "59d93eb2-8227-48cc-a380-662946f817d4",
        name: "Volcanoes",
        slug: "volcanoes",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "cf42b155-0db7-44a8-bd67-d1de0db3e117",
        name: "Earthquakes",
        slug: "earthquakes",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "82b60e6f-48f0-41bf-81c8-08f2a0f670bb",
        name: "Plate Tectonics",
        slug: "plate-tectonics",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "8237ee92-cef8-4fc5-a478-0d0225b813ce",
        name: "Geological Formations",
        slug: "geological-formations",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "8a0e4185-f0ba-4114-8e8e-af8de4aaa072",
        name: "Meteorites",
        slug: "meteorites",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "b1a57309-2c29-4e65-bd26-cea266983ed3",
    name: "Minerals and Gemstones",
    slug: "minerals-and-gemstones",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "ab151b2a-b078-4071-b34a-fafd2bb23137",
        name: "Minerals",
        slug: "minerals",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "f43dde60-b010-4c19-9bb6-026134f7aec1",
        name: "Gemstones",
        slug: "gemstones",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "68194bd3-45ca-4dac-a076-f9c095b2539a",
        name: "Mineraloids",
        slug: "mineraloids",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "00665d4f-1f26-436b-bf89-f33ea4ce2783",
        name: "Mohs Hardness Scale",
        slug: "mohs-hardness-scale",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "047f7a64-08d8-4b23-b472-7394db97a0fa",
        name: "Uses of Minerals",
        slug: "uses-of-minerals",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "02aca375-12a0-4144-8906-741dfb1b7f75",
    name: "Earth Sciences",
    slug: "earth-sciences",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "b7328e51-fca9-489a-9fb4-c49cf3f354fe",
        name: "Earth Science Basics",
        slug: "earth-science-basics",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "945e3956-6068-4342-bae5-65689e8b9cb2",
        name: "Geology",
        slug: "geology",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "7e56dd36-c26a-4d4b-b2f6-74e4698ec7d2",
        name: "Soil and Sediment",
        slug: "soil-and-sediment",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "7481c7c2-0d9c-4f04-b718-d233c7de29ff",
        name: "Natural Disasters",
        slug: "natural-disasters",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "dd095d6e-03a4-4841-98ee-4e4b97b1ce0f",
        name: "Water Bodies",
        slug: "water-bodies",
        showInHeader: true,
        showInFooter: true
      }
    ]
  },
  {
    id: "61798aef-9c1c-4b57-86df-27a915d3c884",
    name: "Maps and Geography",
    slug: "maps-and-geography",
    showInHeader: true,
    showInFooter: true,
    subcategories: [
      {
        id: "bd258775-1043-41c2-a645-ab592ad665ea",
        name: "World Geography",
        slug: "world-geography",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "4d991e3c-e190-494a-8b62-ded17719db7b",
        name: "State Maps",
        slug: "state-maps",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "0718484e-e474-4428-9bae-753c4b21caad",
        name: "Geographical Features",
        slug: "geographical-features",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "5b534549-c9df-4401-bf0f-36f4ca84343b",
        name: "Satellite Imagery",
        slug: "satellite-imagery",
        showInHeader: true,
        showInFooter: true
      },
      {
        id: "f52e4419-ee63-4b6f-a7a7-186aeb44b688",
        name: "Atlas Resources",
        slug: "atlas-resources",
        showInHeader: true,
        showInFooter: true
      }
    ]
  }
]
