/**
 * ✅ EDITABLE FILE - AI Can Modify Values Here
 * 
 * Site Configuration Content
 * This file contains all customizable values for the site
 * 
 * AUTO-GENERATED by Site Builder Template Generator
 * Brand: GeoSphere Insights
 * Generated: 2025-12-01T19:04:22.780Z
 */

import type { SiteConfigSchema, ColorConfigSchema } from './config.schema'

/**
 * Main site configuration
 * Values auto-populated from brand database
 */
export const siteContent: SiteConfigSchema = {
  // Brand identity
  brand: {
    id: "1fbb4037-1eae-482d-996c-1354adbd16bb",
    name: "GeoSphere Insights",
    description: "GeoSphere Insights delivers dynamic and interactive Earth science content, blending cutting-edge technology with engaging educational resources for geology enthusiasts, students, and professionals.",
    url: "https://geosphere-insights-blog.vercel.app",
    logoPath: "/logo.jpg",
    faviconPath: "/logo.jpg",
    ogImagePath: "/logo.jpg",
    mainAppUrl: "https://app.thefaceless.ai"
  },

  // Homepage hero section
  hero: {
    title: "Welcome to GeoSphere Insights",
    subtitle: "GeoSphere Insights offers an unparalleled blend of dynamic Earth science content and cutting-edge technology, providing an engaging and comprehensive learning experience for anyone passionate about geology. Our platform equips users with the tools and knowledge to explore the wonders of the Earth in an interactive and accessible way."
  },

  // Default author information
  author: {
    name: "GeoSphere Insights Team",
    bio: "GeoSphere Insights delivers dynamic and interactive Earth science content, blending cutting-edge technology with engaging educational resources for...",
    role: "Content Creator",
    image: "/logo.jpg"
  },

  // Section headings throughout the site
  sections: {
    topArticles: {
      title: "Featured Articles",
      description: "Handpicked posts just for you"
    },
    recentPosts: {
      title: "Latest Posts"
    },
    categories: {
      title: "Explore Geology & Earth Science Education Topics"
    }
  },

  // Newsletter subscription section
  newsletter: {
    title: "Stay Updated",
    description: "Get the latest from GeoSphere Insights delivered to your inbox",
    disclaimer: "Unsubscribe anytime. We respect your privacy."
  },

  // Blog categories (from brand database)
  categories: [
    { 
      name: "World Geography",
      icon: "FileText",
      slug: "world-geography"
    },
    { 
      name: "Geological Phenomena",
      icon: "FileText",
      slug: "geological-phenomena"
    },
    { 
      name: "Minerals",
      icon: "FileText",
      slug: "minerals"
    },
    { 
      name: "Volcanoes",
      icon: "FileText",
      slug: "volcanoes"
    },
    { 
      name: "Earth Science Basics",
      icon: "Microscope",
      slug: "earth-science-basics"
    },
    { 
      name: "Earthquakes",
      icon: "FileText",
      slug: "earthquakes"
    }
  ],

  // All authors for this brand (with AI-generated portraits)
  authors: [
    {
      id: "0881d4ca-5fe0-4f52-8747-1965c0c67c49",
      name: "Sophia Nguyen",
      bio: "Sophia Nguyen combines her expertise in geospatial technology with a love for visual storytelling. Her contributions are marked by a keen eye for detail and clarity, as she transforms complex data into stunning maps and visuals that captivate and inform. Sophia's analytical yet creative approach ensures that readers not only understand the geographical intricacies but also appreciate the beauty of our planet's landscapes.",
      image: "/api/uploads/brands/1fbb4037-1eae-482d-996c-1354adbd16bb/authors/0881d4ca-5fe0-4f52-8747-1965c0c67c49/portrait-1764596874589.png",
      role: "Geospatial Analyst and Cartographer"
    },
    {
      id: "29f8c603-6cd2-4d23-939c-0e654a32bd4b",
      name: "Alex Rivera",
      bio: "Alex Rivera is a passionate Earth science communicator with a flair for uncovering the human stories behind geological discoveries. Their journalistic approach is both investigative and narrative-driven, providing readers with a vivid exploration of natural phenomena and the latest scientific breakthroughs. Alex's engaging voice and sharp insights make even the most technical topics relatable and exciting to explore.",
      image: "/api/uploads/brands/1fbb4037-1eae-482d-996c-1354adbd16bb/authors/29f8c603-6cd2-4d23-939c-0e654a32bd4b/portrait-1764596845516.png",
      role: "Earth Science Journalist"
    },
    {
      id: "b5d2d001-cc33-4262-9434-aba9f8664b58",
      name: "Dr. Emily Carson",
      bio: "Dr. Emily Carson brings a wealth of knowledge from her career in academia and field research. Her writing style is both authoritative and approachable, making complex geological concepts accessible to a wide audience. With a knack for storytelling, she engages readers by weaving scientific facts with intriguing real-world examples, fostering a deeper appreciation for Earth's dynamic processes.",
      image: "/api/uploads/brands/1fbb4037-1eae-482d-996c-1354adbd16bb/authors/b5d2d001-cc33-4262-9434-aba9f8664b58/portrait-1764596815465.png",
      role: "Geological Educator and Researcher"
    }
  ]
}

/**
 * Color configuration
 * Brand colors in oklch() format for consistent rendering
 * Auto-converted from brand hex colors
 */
export const colorContent: ColorConfigSchema = {
  // Light mode colors
  light: {
    primary: "#2563EB",      // #2563EB
    secondary: "#64748B",  // #64748B
    accent: "#F59E0B"         // #F59E0B
  },

  // Dark mode colors (auto-lightened for contrast)
  dark: {
    primary: "#2563EB",
    secondary: "#64748B",
    accent: "#F59E0B"
  }
}
